Update deploy_argo_helm_gunicorn_nginx_EKS.yml

diff --git a/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml b/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
--- a/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
+++ b/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
@@ -121,7 +121,6 @@ jobs:
         helm install argocd argo/argo-cd --namespace argocd --create-namespace || { echo "Failed to install Argo CD"; exit 1; }
       
         # Wait for argocd-server to be deployed
-          # Wait for argocd-server to be deployed
         echo "Waiting for argocd-server to be ready..."
         for i in {1..60}; do
           if kubectl get deployment argocd-server -n argocd -o jsonpath='{.status.readyReplicas}' | grep -q '1'; then
@@ -134,11 +133,24 @@ jobs:
         done || { echo "argocd-server not ready after waiting"; exit 1; }
       
         # Expose Argo CD API Server via an AWS Load Balancer
-        kubectl patch svc argocd-server -n argocd --type='merge' -p '{"spec": {"type": "LoadBalancer"}}' || { echo "Failed to patch svc"; exit 1; }
+        # Attempt to patch the service
+        echo "Attempting to patch svc argocd-server to LoadBalancer..."
+        kubectl patch svc argocd-server -n argocd --type='merge' -p '{"spec": {"type": "LoadBalancer"}}'
+
+        # Wait for 5 minutes
+        echo "Waiting for 5 minutes to allow patching to take effect..."
+        sleep 300  # 300 seconds = 5 minutes
+
+        # Check if the patching was successful
+        if kubectl get svc argocd-server -n argocd -o jsonpath='{.spec.type}' | grep -q 'LoadBalancer'; then
+          echo "Patching svc argocd-server to LoadBalancer was successful"
+        else
+          echo "Failed to patch svc to LoadBalancer type after waiting"
+          exit 1
       
         # Get the Load Balancer of Argo CD API Server URL
         echo "Waiting for Load Balancer hostname..."
-        for i in {1..30}; do
+        for i in {1..60}; do
           Argo_URL=$(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
           if [ -n "$Argo_URL" ]; then
             echo "Load Balancer hostname is ready: $Argo_URL"
@@ -147,7 +159,7 @@ jobs:
             echo "Waiting for Load Balancer hostname... (Attempt $i)"
             sleep 10
           fi
-        done || { echo "Failed to get Argo URL"; exit 1; }
+        done || { echo "Failed to get Argo URL after waiting"; exit 1; }
       
         # Access the Argo CD UI and get the password
         Argo_OriginPW=\$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d) || { echo "Failed to get Argo password"; exit 1; }
