Update deploy_argo_helm_gunicorn_nginx_EKS.yml

diff --git a/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml b/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
--- a/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
+++ b/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
@@ -318,12 +318,22 @@ jobs:
         echo $REGION
         
         sudo sed -i "s/\*\*\*/$REGION/" hostname.txt
+
+        # Print contents of the files
+        echo "Hostname: $(cat /home/ec2-user/hostname.txt)"
+        echo "Password: $(cat /home/ec2-user/secret.txt)"
+
+        # Update a by replacing *** with the value of REGION
+        b=\$(echo "\$a" | sed "s/\*\*\*/$REGION/")
+
+        # Output the updated value of a
+        echo \"Updated a: \$b\"
         
         # Access the Argo CD UI and get the password
         kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d > secret.txt
       
         # Log into Argo with an original password
-        argocd login \$(cat /home/ec2-user/hostname.txt) --username admin --password \$(cat /home/ec2-user/secret.txt) --insecure || { echo "Failed to login to Argo"; exit 1; } 
+        argocd login \$(cat /home/ec2-user/hostname.txt)\ --username admin --password \$(cat /home/ec2-user/secret.txt) --insecure || { echo "Failed to login to Argo"; exit 1; } 
       
         # Update password in Argo CD
         argocd account update-password --current-password \$(cat /home/ec2-user/secret.txt) --new-password ${{ secrets.ARGOCD_NEW_PASSWORD }} || { echo "Failed to update Argo password"; exit 1; }
