Update deploy_argo_helm_gunicorn_nginx_EKS.yml

diff --git a/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml b/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
--- a/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
+++ b/.github/workflows/deploy_argo_helm_gunicorn_nginx_EKS.yml
@@ -308,20 +308,27 @@ jobs:
         a=\$(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
         echo \"The hostname is: \$a\"
 
-        
-        
-        # Access the Argo CD UI and get the password
-        kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d > secret.txt
-      
-        # Log into Argo with an original password
-        argocd login a6568b00361234dbcad17944df88d3b3-1182343919.ap-southeast-2.elb.amazonaws.com --username admin --password \$(cat /home/ec2-user/secret.txt) --insecure || { echo "Failed to login to Argo"; exit 1; } 
-      
-        # Update password in Argo CD
-        argocd account update-password --current-password \$(cat /home/ec2-user/secret.txt) --new-password ${{ secrets.ARGOCD_NEW_PASSWORD }} || { echo "Failed to update Argo password"; exit 1; }
-      
-        # Log into Argo with a new password
-        argocd login a6568b00361234dbcad17944df88d3b3-1182343919.ap-southeast-2.elb.amazonaws.com --username admin --password ${{ secrets.ARGOCD_NEW_PASSWORD }} || { echo "Failed to login with new Argo password"; exit 1; }
-      
+        result=\$( aws elb describe-load-balancers --region ap-southeast-2 --query 'LoadBalancerDescriptions[*].DNSName' --output text)
+        echo \"The load balancer is: \$result\"
+
+
+        # Try logging into Argo CD with the original password
+        if argocd login a6568b00361234dbcad17944df88d3b3-1182343919.ap-southeast-2.elb.amazonaws.com --username admin --password $(cat /home/ec2-user/secret.txt) --insecure; then
+          echo "Logged in with the original password."
+          echo "Update the password"
+          argocd account update-password --current-password \$(cat /home/ec2-user/secret.txt) --new-password ${{ secrets.ARGOCD_NEW_PASSWORD }} || { echo "Failed to update Argo password"; exit 1; }
+        else
+          echo "Failed to login with the original password. Trying with the new password..."
+  
+          # Try logging into Argo CD with the new password
+          if argocd login a6568b00361234dbcad17944df88d3b3-1182343919.ap-southeast-2.elb.amazonaws.com --username admin --password ${{ secrets.ARGOCD_NEW_PASSWORD }} --insecure; then
+            echo "Logged in with the new password."
+          else
+            echo "Failed to login with the new Argo password."
+            exit 1
+          fi
+        fi
+           
         # Retrieve the name of the current Kubernetes context
         ContextName=\$(kubectl config current-context) || { echo "Failed to get Kubernetes context"; exit 1; }
       
